name 'logicminds-bmclib'
version '0.1.0'
author 'Corey Osman'
license 'LGPLv2.1'
project_page 'http://www.github.com/logicminds/bmclib'
source 'https://github.com/logicminds/bmclib.git'
summary 'The bmclib is a module that automates deployment of ipmi devices and provides other useful types.'
description 'The BMClib is a puppet library that provides BMC related facts as well as a bmc and bmcuser type. It also installs and starts the OpenIPMI service. Currently the only provider available is ipmitool. However, in the future additional provider types will include freeipmi, hponcfg, and other oem related tools.'
